config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shops do
    collection do
      get 'top'
    end
    resources :reviews
  end
  root "shops#top"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :shops

  validates :name, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shops

  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :shop
  belongs_to :user

  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :description, presence: true
  validates :evaluation, presence: true

  scope :find_new_review, -> { order(created_at: :desc).limit(5) }
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :genre
  belongs_to :area
  belongs_to :user
  has_many :reviews

  mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :genre_id, presence: true
  validates :area_id, presence: true
  validates :user_id, presence: true
  validates :review_avg, presence: true
  validates :budget_min , presence: true, :numericality => { :less_than => :budget_max }
  validates :budget_max, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shops
  has_many :reviews

  validates :nick_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :image])

    devise_parameter_sanitizer.permit(:account_update, keys: [:nick_name, :image])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @shop = Shop.find(params[:shop_id])
    @review = @shop.reviews.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to [@review.shop, @review]
    else
      #@reviewに紐ずくshopを抽出
      @shop = @review.shop
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
    @shop = @review.shop
  end

  def edit
    @review = Review.find(params[:id])
    @shop = @review.shop
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to [@review.shop, @review]
    else
      @shop = @review.shop
      render :edit
    end
  end



private

  def review_params
    params.require(:review).permit(:title, :description, :evaluation, :image, :shop_id, :user_id)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def top
     @q = Shop.ransack(params[:q])
     @shops = @q.result.page(params[:page])
     @reviews = Review.find_new_review
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to @shop
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])

  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to @shop
    else
      render :edit
    end
  end

  def show
    @shop = Shop.find(params[:id])
    @reviews = @shop.reviews.page(params[:page]).per(3)
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
  end

  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result.page(params[:page])
  end


  private

  def shop_params
    params.require(:shop).permit(:name, :description, :image, :budget_min,
      :budget_max, :genre_id, :area_id, :user_id, :review_avg)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def evaluation_star(evaluation)
    "☆" * evaluation
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PakuLog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">PakuLogとは</a></li>
        <% if user_signed_in? %>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "会員登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pakulog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render partial: 'layouts/header' %>
   <div class="container">
     <%= yield %>
   </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with model: [shop, review], local: true do |form| %>
  <% if review.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= review.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %><br />
    <%= form.text_field :title, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br />
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field" id="star">
    <%= form.label :evaluation %>
    <%= form.hidden_field :evaluation, id: :evaluation_star %>
  </div>

  <div class="form-group">
    <%= form.label :image %><br>
    <%= image_tag review.image if review.persisted? %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <%= form.hidden_field :shop_id, value: review.shop_id %>

  <%= form.hidden_field :user_id, value: current_user.id %>


  <div class="form-group">
    <%= form.submit "投稿する！", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/reviews/_list.html.erb
<% reviews.each do |review| %>
  <hr>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <!-- reviewに紐づくuser 画像 -->
      <% if review.user.image.present? %>
        <%= image_tag review.user.image, class: "user_icon" %>
      <% else %>
        <%= image_tag "default_user.png", class: "user_icon" %>
      <% end %>
      <!-- reviewsに紐づくuserの名前 -->
      <%= review.user.nick_name %>
      <!-- reviewsのtitle -->
      <%= link_to review.title, shop_review_path(review.shop, review) %>
      <!-- reviewsのdescription -->
      <%= truncate(review.description, length: 50) %>
      <%= link_to "もっと見る", shop_review_path(review.shop, review), class: "btn btn-warning"%>
      <!-- reviewsのimage -->
      <%= image_tag review.image, class: "img-responsive img-thumbnail" %>
      <!-- reviewsのevaluation -->
      <%= evaluation_star(review.evaluation) %>
    </div>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h2>口コミ編集</h2>
    <%= render partial: 'form', locals: { shop: @shop, review: @review } %>
  </div>
</div>

<script>
$('#star').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  scoreName: 'review[evaluation]'
});
</script>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h2>口コミ投稿</h2>
    <%= render partial: 'form', locals: { shop: @shop, review: @review } %>
  </div>
</div>

<script>
$('#star').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  scoreName: 'review[evaluation]'
});
</script>

app/views/reviews/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>口コミ詳細</h1>
    <dl>
      <dt>名前</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @shop.name%></dd>
      <dt>タイトル</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @review.title %></dd>
      <dt>詳細</dt>
      <dd style="margin:0px 0px 10px 20px"><%= simple_format(@review.description) %></dd>
      <dt>レビュー</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @review.evaluation %></dd>
      <dt>画像</dt>
      <dd style="margin:0px 0px 10px 20px"><%= image_tag @shop.image %></dd>
    </dl>
    <%= link_to '戻る', top_shops_path, class: "btn btn-default" %>

    <% if @review.user_id == current_user.id %>
      <%= link_to '編集', edit_shop_review_path(@shop, @review), class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/shops/_form.html.erb
<%= form_with model: shop, local: true do |form| %>
  <% if shop.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= shop.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :image %><br>
    <%= image_tag shop.image if shop.persisted? %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :budget_min %><br>
    <%= form.number_field :budget_min, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :budget_max %><br>
    <%= form.number_field :budget_max, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :genre_id %><br>
    <%= form.collection_select :genre_id, Genre.all, :id, :name , { include_blank: "ジャンルを選択してください" },  { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :area_id %><br>
    <%= form.collection_select :area_id, Area.all, :id, :name , { include_blank: "エリアを選択してください" },  { class: "form-control" } %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id, class: "form-control" %>

  <%= form.submit class: "btn btn-default" %>
<% end %>

app/views/shops/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レストランの編集</h1>
    <%= render partial: 'form', locals: { shop: @shop } %>
    <!-- 下記の2行を追加 -->
    <button type="button" style="margin-top:5px;" class="btn btn-default" data-toggle="modal" data-target="#delete-shop">レストランを削除する</button>
    <%= link_to '戻る', shop_path(@shop),  style: "margin-top:5px;", class: "btn btn-default" %>
  </div>
</div>

<div class="modal fade" id="delete-shop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">レストランの削除</h4>
      </div>
      <div class="modal-body">
        <p><%= @shop.name %>削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @shop, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h1>レストラン一覧</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <p>レストラン情報が表示されます。</p>
  </div>
  <div class="col-md-10 col-md-offset-1">
    <%= link_to 'レストラン登録', new_shop_path, class: "btn btn-info pull-right" %>
  </div>
</div>
<% @shops.each do |shop| %>
  <hr>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="col-md-4">
        <%= image_tag shop.image, class: "img-responsive img-thumbnail" %>
      </div>
      <div class="col-md-8">
        <h2><%= link_to shop.name, shop_path(shop) %></h2>
        <div class="shops-index-description">
          <div>詳細: <%= truncate(shop.description, length: 50) %></div>
          <div>評価: <%= shop.review_avg %></div>
          <div>予算: <%= shop.budget_min %> 〜 <%= shop.budget_max %> (円)</div>
          <div>ジャンル: <%= shop.genre.name %></div>
          <div>エリア: <%= shop.area.name %></div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shops/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レストラン新規登録</h1>
    <%= render partial: 'form', locals: { shop: @shop } %>
  </div>
</div>

app/views/shops/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レストラン詳細</h1>
    <dl>
      <dt>店名</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @shop.name %></dd>
      <dt>詳細</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @shop.description %></dd>
      <dt>画像</dt>
      <dd style="margin:0px 0px 10px 20px"><%= image_tag @shop.image %></dd>
      <dt>予算下限</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @shop.budget_min %></dd>
      <dt>予算上限</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @shop.budget_max %></dd>
      <dt>ジャンル</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @shop.genre.name %></dd>
      <dt>エリア</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @shop.area.name%></dd>
      <dt>レビュー</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @shop.review_avg %></dd>
    </dl>
    <%= link_to '編集', edit_shop_path(@shop), class: "btn btn-default" %>
    <%= link_to '戻る', top_shops_path, class: "btn btn-default" %>
  </div>
</div>

<div class="row">
  <div class="text-right">
    <%= link_to "口コミ投稿", new_shop_review_path(@shop), class: "btn btn-warning" %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>口コミ一覧</h2>
    <%= render partial: 'reviews/list', locals: { reviews: @reviews } %>
    <div class="text-center">
      <%= paginate @reviews %>
    </div>
  </div>
</div>

app/views/shops/top.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= search_form_for @q do |f| %>
      <div class="input-group">
        <%= f.search_field :name_or_description_cont, class: "form-control", placeholder: "キーワード[例 焼き肉、店名]" %>
        <span class="input-group-btn">
          <%= f.submit "検索", class: "btn btn-primary" %>
        </span>
      </div>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>レストランを探す</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="row m-lr-20">
      <div class="col-md-3">
        <%= image_tag '/images/iwate.jpg', class: "img-responsive" %>
      </div>
      <div class="col-md-3">
        <%= image_tag '/images/tokyo.jpg', class: "img-responsive" %>
      </div>
      <div class="col-md-3">
        <%= image_tag '/images/osaka.jpg', class: "img-responsive" %>
      </div>
      <div class="col-md-3">
        <%= image_tag '/images/hiroshima.jpg', class: "img-responsive" %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>新着口コミ</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render partial: 'reviews/list', locals: { reviews: @reviews } %>
  </div>
</div>